baseURL: "https://husnaram.github.io/"
languageCode: en-us
title: The HoR
copyright: "Â© Husna"

# Code Highlight
pygmentsstyle: "monokai"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

paginate: 5 # articles per page

params:
    mode: auto
    useCDN: false
    subtitle: 'a seasoned enthusiast of developer'
    sayHello: "Hello folks"
    intro: "Hi! I'm Husna by the way. An enthusiasts in web programming. But not a professional, and still want be the expert, that's why i'm learning, always!"
    mySkills:
    - HTML/CSS
    - Tailwindcss
    - Javascript
    - Laravel
    - PHP
    - Golang
    - MySQL
    social:
        - name: GitHub
          icon: github
          url: 'https://github.com/husnaram'
        - name: Twitter
          icon: twitter
          url: 'https://twitter.com/husna_ram/'

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: All posts
          url: /posts
          weight: 2
        - name: Tags
          url: /tags
          weight: 4
